import { FieldType, IField, IFieldAction } from "types/types";

import { ItemLevel } from "components/core/Game/Inventory/InventoryItem";

// import {FieldStatus} from ""

export const testField: IField = {
  fieldId: 1,
  level: ItemLevel.ECONOM,
  fieldGroup: 1,
  imgSrc: "testImgSrc",
  fieldGroupName: "testGroupName",
  fieldPosition: 1,
  name: "testName",
  type: FieldType.COMPANY,
  price: {
    branchPrice: 1000,
    buyoutPrice: 900,
    pledgePrice: 500,
    startPrice: 2000,
  },
  rent: {
    baseRent: 200,
    monopolyRent: 250,
    oneStar: 300,
    twoStar: 1000,
    freeStar: 1500,
    fourStar: 2000,
    bigStar: 3000,
  },
};

export const testOwnedField: IField = {
  status: {
    branches: 0,
    isMonopoly: false,
    fieldId: 1,
    userId: 1,
    mortgaged: 0,
    fieldActions: [
      IFieldAction.MORTGAGE,
      IFieldAction.LEVEL_UP,
      IFieldAction.LEVEL_DOWN,
    ],
  },
  fieldId: 1,
  fieldPosition: 1,
  level: ItemLevel.ECONOM,
  description: "testDescription",
  name: "testName",
  type: FieldType.COMPANY,
  price: {
    branchPrice: 1000,
    buyoutPrice: 900,
    pledgePrice: 500,
    startPrice: 2000,
  },
  rent: {
    baseRent: 200,
    monopolyRent: 250,
    oneStar: 300,
    twoStar: 1000,
    freeStar: 1500,
    fourStar: 2000,
    bigStar: 3000,
  },
};

export const testStaredField: IField = {
  status: {
    branches: 0,
    isMonopoly: false,
    fieldId: 1,
    userId: 1,
    mortgaged: 0,
    fieldActions: [
      IFieldAction.MORTGAGE,
      IFieldAction.LEVEL_UP,
      IFieldAction.LEVEL_DOWN,
    ],
  },
  fieldId: 1,
  level: ItemLevel.ECONOM,
  fieldPosition: 1,
  name: "testName",
  type: FieldType.COMPANY,
  price: {
    branchPrice: 1000,
    buyoutPrice: 900,
    pledgePrice: 500,
    startPrice: 2000,
  },
  rent: {
    baseRent: 200,
    monopolyRent: 250,
    oneStar: 300,
    twoStar: 1000,
    freeStar: 1500,
    fourStar: 2000,
    bigStar: 3000,
  },
};

export const testMortgagedField: IField = {
  status: {
    branches: 0,
    isMonopoly: false,
    fieldId: 1,
    userId: 1,
    mortgaged: 1,
    fieldActions: [IFieldAction.UNMORTGAGE],
  },
  fieldId: 1,
  level: ItemLevel.ECONOM,
  fieldPosition: 1,
  name: "testName",
  type: FieldType.COMPANY,
  price: {
    branchPrice: 1000,
    buyoutPrice: 900,
    pledgePrice: 500,
    startPrice: 2000,
  },
  rent: {
    baseRent: 200,
    monopolyRent: 250,
    oneStar: 300,
    twoStar: 1000,
    freeStar: 1500,
    fourStar: 2000,
    bigStar: 3000,
  },
};

export const testJailField: IField = {
  fieldId: 10,
  level: ItemLevel.ECONOM,
  fieldPosition: 10,
  name: "jail",
  type: FieldType.JAIL,
  fieldCorner: 2,
  fieldLine: 1,
  isJail: true,
};

export default (): IField[] => [
  {
    fieldId: 1,
    fieldPosition: 0,
    fieldSpecial: undefined,
    fieldGroup: null,
    fieldCorner: 0,
    fieldLine: null,
    isJail: false,
    level: 0,
    imgSrc: "fields/special/start.png",
    name: "start",
    description: undefined,
    fieldGroupName: "IT компании",
    type: FieldType.START,
    currency: "$",
    price: undefined,
    rent: undefined,
  },
  {
    fieldId: 2,
    fieldPosition: 1,
    fieldSpecial: undefined,
    fieldGroup: 1,
    fieldCorner: undefined,
    fieldLine: 0,
    isJail: false,
    level: 0,
    imgSrc: "fields/brands/1_perfumery/chanel.svg",
    name: "chanel",
    description: "Стройте филиалы, чтобы увеличить ренту",
    fieldGroupName: "Парфюмерия",
    type: FieldType.COMPANY,
    currency: "$",
    price: {
      startPrice: 600,
      pledgePrice: 300,
      buyoutPrice: 360,
      branchPrice: 500,
    },
    rent: {
      monopolyRent: 30,
      baseRent: 20,
      oneStar: 100,
      twoStar: 300,
      freeStar: 900,
      fourStar: 1600,
      bigStar: 2500,
      paymentMultiplier: 0,
    },
  },
  {
    fieldId: 3,
    fieldPosition: 2,
    fieldSpecial: 1,
    fieldGroup: null,
    fieldCorner: undefined,
    fieldLine: 0,
    isJail: false,
    level: 0,
    imgSrc: "fields/special/tax_income.png",
    name: "tax_income",
    description: "testDescription",
    fieldGroupName: "IT компании",
    type: FieldType.TAX,
    currency: "$",
    price: { startPrice: 0, pledgePrice: 0, buyoutPrice: 0, branchPrice: 0 },
    rent: {
      monopolyRent: 0,
      baseRent: 2000,
      oneStar: 0,
      twoStar: 0,
      freeStar: 0,
      fourStar: 0,
      bigStar: 0,
      paymentMultiplier: 0,
    },
  },
  {
    fieldId: 4,
    fieldPosition: 3,
    fieldSpecial: null,
    fieldGroup: 1,
    fieldCorner: undefined,
    fieldLine: 0,
    isJail: false,
    level: 0,
    imgSrc: "fields/brands/1_perfumery/hugo_boss.svg",
    name: "hugo_boss",
    description: "Стройте филиалы, чтобы увеличить ренту",
    fieldGroupName: "Парфюмерия",
    type: FieldType.COMPANY,
    currency: "$",
    price: {
      startPrice: 600,
      pledgePrice: 300,
      buyoutPrice: 360,
      branchPrice: 500,
    },
    rent: {
      monopolyRent: 60,
      baseRent: 40,
      oneStar: 200,
      twoStar: 200,
      freeStar: 1800,
      fourStar: 3200,
      bigStar: 4500,
      paymentMultiplier: 0,
    },
  },
  {
    fieldId: 5,
    fieldPosition: 4,
    fieldSpecial: null,
    fieldGroup: 1,
    fieldCorner: undefined,
    fieldLine: 0,
    isJail: false,
    level: 0,
    imgSrc: "fields/brands/1_perfumery/hugo_boss.svg",
    name: "iv_roche",
    description: "Стройте филиалы, чтобы увеличить ренту",
    fieldGroupName: "Парфюмерия",
    type: FieldType.COMPANY,
    currency: "$",
    price: {
      startPrice: 600,
      pledgePrice: 300,
      buyoutPrice: 360,
      branchPrice: 500,
    },
    rent: {
      monopolyRent: 60,
      baseRent: 40,
      oneStar: 200,
      twoStar: 200,
      freeStar: 1800,
      fourStar: 3200,
      bigStar: 4500,
      paymentMultiplier: 0,
    },
  },
  {
    fieldId: 6,
    fieldPosition: 5,
    fieldSpecial: null,
    fieldGroup: 0,
    fieldCorner: undefined,
    fieldLine: 0,
    isJail: false,
    level: 0,
    imgSrc: "fields/brands/0_auto/mercedes.svg",
    name: "mercedes",
    description:
      "Рента зависит от количества автомобилей, которыми Вы владеете",
    fieldGroupName: "Автомобили",
    type: FieldType.AUTO,
    currency: "$",
    price: {
      startPrice: 2000,
      pledgePrice: 1000,
      buyoutPrice: 1200,
      branchPrice: 0,
    },
    rent: {
      monopolyRent: 0,
      baseRent: 250,
      oneStar: 500,
      twoStar: 1000,
      freeStar: 2000,
      fourStar: 0,
      bigStar: 0,
      paymentMultiplier: 0,
    },
  },
  {
    fieldId: 7,
    fieldPosition: 6,
    fieldSpecial: null,
    fieldGroup: 2,
    fieldCorner: undefined,
    fieldLine: 0,
    isJail: false,
    level: 0,
    imgSrc: "fields/brands/2_clothing/adidas.svg",
    name: "adidas",
    description: "Стройте филиалы, чтобы увеличить ренту",
    fieldGroupName: "Одежда",
    type: FieldType.COMPANY,
    currency: "$",
    price: {
      startPrice: 1000,
      pledgePrice: 500,
      buyoutPrice: 600,
      branchPrice: 500,
    },
    rent: {
      monopolyRent: 90,
      baseRent: 60,
      oneStar: 300,
      twoStar: 900,
      freeStar: 2700,
      fourStar: 4000,
      bigStar: 5500,
      paymentMultiplier: 0,
    },
  },
  {
    fieldId: 8,
    fieldPosition: 7,
    fieldSpecial: 1,
    fieldGroup: null,
    fieldCorner: undefined,
    fieldLine: 0,
    isJail: false,
    level: 0,
    imgSrc: "fields/special/chance.png",
    name: "chance",
    description: "testDescription",
    fieldGroupName: "IT компании",
    type: FieldType.CHANCE,
    currency: "$",
    price: null,
    rent: null,
  },
  {
    fieldId: 9,
    fieldPosition: 8,
    fieldSpecial: null,
    fieldGroup: 2,
    fieldCorner: undefined,
    fieldLine: 0,
    isJail: false,
    level: 0,
    imgSrc: "fields/brands/2_clothing/puma.svg",
    name: "puma",
    description: "Стройте филиалы, чтобы увеличить ренту",
    fieldGroupName: "Одежда",
    type: FieldType.COMPANY,
    currency: "$",
    price: {
      startPrice: 1000,
      pledgePrice: 500,
      buyoutPrice: 600,
      branchPrice: 500,
    },
    rent: {
      monopolyRent: 90,
      baseRent: 60,
      oneStar: 300,
      twoStar: 900,
      freeStar: 2700,
      fourStar: 4000,
      bigStar: 5500,
      paymentMultiplier: 0,
    },
  },
  {
    fieldId: 10,
    fieldPosition: 9,
    fieldSpecial: null,
    fieldGroup: 2,
    fieldCorner: undefined,
    fieldLine: 0,
    isJail: false,
    level: 0,
    imgSrc: "fields/brands/2_clothing/lacoste.svg",
    name: "lacoste",
    description: "Стройте филиалы, чтобы увеличить ренту",
    fieldGroupName: "Одежда",
    type: FieldType.COMPANY,
    currency: "$",
    price: {
      startPrice: 1200,
      pledgePrice: 600,
      buyoutPrice: 720,
      branchPrice: 500,
    },
    rent: {
      monopolyRent: 120,
      baseRent: 80,
      oneStar: 400,
      twoStar: 1000,
      freeStar: 3000,
      fourStar: 4500,
      bigStar: 6000,
      paymentMultiplier: 0,
    },
  },
  {
    fieldId: 11,
    fieldPosition: 10,
    fieldSpecial: null,
    fieldGroup: null,
    fieldCorner: 1,
    fieldLine: null,
    isJail: true,
    level: 0,
    imgSrc: "",
    name: "jail",
    description: "testDescription",
    fieldGroupName: "IT компании",
    type: FieldType.TAKE_REST,
    currency: "$",
    price: null,
    rent: null,
  },
  {
    fieldId: 12,
    fieldPosition: 11,
    fieldSpecial: null,
    fieldGroup: 3,
    fieldCorner: undefined,
    fieldLine: 1,
    isJail: false,
    level: 0,
    imgSrc: "fields/brands/3_web/vk.svg",
    name: "vk",
    description: "Стройте филиалы, чтобы увеличить ренту",
    fieldGroupName: "Веб-сервисы",
    type: FieldType.COMPANY,
    currency: "$",
    price: {
      startPrice: 1400,
      pledgePrice: 700,
      buyoutPrice: 840,
      branchPrice: 750,
    },
    rent: {
      monopolyRent: 150,
      baseRent: 100,
      oneStar: 500,
      twoStar: 1500,
      freeStar: 4500,
      fourStar: 6250,
      bigStar: 7500,
      paymentMultiplier: 0,
    },
  },
  {
    fieldId: 13,
    fieldPosition: 12,
    fieldSpecial: null,
    fieldGroup: 9,
    fieldCorner: undefined,
    fieldLine: 1,
    isJail: false,
    level: 0,
    imgSrc: "fields/brands/9_games/rockstar_games.svg",
    name: "rockstar_games",
    description: "Рента зависит от количества IT компаний",
    fieldGroupName: "IT компании",
    type: FieldType.IT,
    currency: "x",
    price: {
      startPrice: 1500,
      pledgePrice: 750,
      buyoutPrice: 900,
      branchPrice: 0,
    },
    rent: {
      monopolyRent: 0,
      baseRent: 100,
      oneStar: 250,
      twoStar: 0,
      freeStar: 0,
      fourStar: 0,
      bigStar: 0,
      paymentMultiplier: 1,
    },
  },
  {
    fieldId: 14,
    fieldPosition: 13,
    fieldSpecial: null,
    fieldGroup: 3,
    fieldCorner: undefined,
    fieldLine: 1,
    isJail: false,
    level: 0,
    imgSrc: "fields/brands/3_web/facebook.svg",
    name: "facebook",
    description: "Стройте филиалы, чтобы увеличить ренту",
    fieldGroupName: "Веб-сервисы",
    type: FieldType.COMPANY,
    currency: "$",
    price: {
      startPrice: 1400,
      pledgePrice: 700,
      buyoutPrice: 840,
      branchPrice: 750,
    },
    rent: {
      monopolyRent: 150,
      baseRent: 100,
      oneStar: 500,
      twoStar: 1500,
      freeStar: 4500,
      fourStar: 6250,
      bigStar: 7500,
      paymentMultiplier: 0,
    },
  },
  {
    fieldId: 15,
    fieldPosition: 14,
    fieldSpecial: null,
    fieldGroup: 3,
    fieldCorner: undefined,
    fieldLine: 1,
    isJail: false,
    level: 0,
    imgSrc: "fields/brands/3_web/twitter.svg",
    name: "twitter",
    description: "Стройте филиалы, чтобы увеличить ренту",
    fieldGroupName: "Веб-сервисы",
    type: FieldType.COMPANY,
    currency: "$",
    price: {
      startPrice: 1600,
      pledgePrice: 800,
      buyoutPrice: 960,
      branchPrice: 750,
    },
    rent: {
      monopolyRent: 180,
      baseRent: 120,
      oneStar: 600,
      twoStar: 1800,
      freeStar: 5000,
      fourStar: 7000,
      bigStar: 8000,
      paymentMultiplier: 0,
    },
  },
  {
    fieldId: 16,
    fieldPosition: 15,
    fieldSpecial: null,
    fieldGroup: 0,
    fieldCorner: undefined,
    fieldLine: 1,
    isJail: false,
    level: 0,
    imgSrc: "fields/brands/0_auto/audi.svg",
    name: "audi",
    description:
      "Рента зависит от количества автомобилей, которыми Вы владеете",
    fieldGroupName: "Автомобили",
    type: FieldType.AUTO,
    currency: "$",
    price: {
      startPrice: 2000,
      pledgePrice: 1000,
      buyoutPrice: 1200,
      branchPrice: 0,
    },
    rent: {
      monopolyRent: 0,
      baseRent: 250,
      oneStar: 500,
      twoStar: 1000,
      freeStar: 2000,
      fourStar: 0,
      bigStar: 0,
      paymentMultiplier: 0,
    },
  },
  {
    fieldId: 17,
    fieldPosition: 16,
    fieldSpecial: null,
    fieldGroup: 4,
    fieldCorner: undefined,
    fieldLine: 1,
    isJail: false,
    level: 0,
    imgSrc: "fields/brands/4_drinks/coca_cola.svg",
    name: "coca_cola",
    description: "Стройте филиалы, чтобы увеличить ренту",
    fieldGroupName: "Напитки",
    type: FieldType.COMPANY,
    currency: "$",
    price: {
      startPrice: 1800,
      pledgePrice: 900,
      buyoutPrice: 108,
      branchPrice: 1000,
    },
    rent: {
      monopolyRent: 210,
      baseRent: 140,
      oneStar: 700,
      twoStar: 2000,
      freeStar: 5600,
      fourStar: 7600,
      bigStar: 9700,
      paymentMultiplier: 0,
    },
  },
  {
    fieldId: 18,
    fieldPosition: 17,
    fieldSpecial: 1,
    fieldGroup: null,
    fieldCorner: undefined,
    fieldLine: 1,
    isJail: false,
    level: 0,
    imgSrc: "fields/special/chance.png",
    name: "chance",
    description: "testDescription",
    fieldGroupName: "IT компании",
    type: FieldType.CHANCE,
    currency: "$",
    price: null,
    rent: null,
  },
  {
    fieldId: 19,
    fieldPosition: 18,
    fieldSpecial: null,
    fieldGroup: 4,
    fieldCorner: undefined,
    fieldLine: 1,
    isJail: false,
    level: 0,
    imgSrc: "fields/brands/4_drinks/pepsi.svg",
    name: "pepsi",
    description: "Стройте филиалы, чтобы увеличить ренту",
    fieldGroupName: "Напитки",
    type: FieldType.COMPANY,
    currency: "$",
    price: {
      startPrice: 1800,
      pledgePrice: 900,
      buyoutPrice: 1080,
      branchPrice: 1000,
    },
    rent: {
      monopolyRent: 210,
      baseRent: 140,
      oneStar: 700,
      twoStar: 2000,
      freeStar: 5600,
      fourStar: 7600,
      bigStar: 9700,
      paymentMultiplier: 0,
    },
  },
  {
    fieldId: 20,
    fieldPosition: 19,
    fieldSpecial: null,
    fieldGroup: 4,
    fieldCorner: undefined,
    fieldLine: 1,
    isJail: false,
    level: 0,
    imgSrc: "fields/brands/4_drinks/fanta.svg",
    name: "fanta",
    description: "Стройте филиалы, чтобы увеличить ренту",
    fieldGroupName: "Напитки",
    type: FieldType.COMPANY,
    currency: "$",
    price: {
      startPrice: 2000,
      pledgePrice: 1000,
      buyoutPrice: 1200,
      branchPrice: 1000,
    },
    rent: {
      monopolyRent: 240,
      baseRent: 160,
      oneStar: 800,
      twoStar: 2200,
      freeStar: 6000,
      fourStar: 8000,
      bigStar: 10000,
      paymentMultiplier: 0,
    },
  },
  {
    fieldId: 21,
    fieldPosition: 20,
    fieldSpecial: 1,
    fieldGroup: null,
    fieldCorner: 2,
    fieldLine: null,
    isJail: false,
    level: 0,
    imgSrc: "fields/special/jackpot.svg",
    name: "casino",
    description: "testDescription",
    fieldGroupName: "IT компании",
    type: FieldType.CASINO,
    currency: "$",
    price: null,
    rent: null,
  },
  {
    fieldId: 22,
    fieldPosition: 21,
    fieldSpecial: null,
    fieldGroup: 5,
    fieldCorner: undefined,
    fieldLine: 2,
    isJail: false,
    level: 0,
    imgSrc: "fields/brands/5_airlines/american_airlines.svg",
    name: "american_airlines",
    description: "Стройте филиалы, чтобы увеличить ренту",
    fieldGroupName: "Авиалинии",
    type: FieldType.COMPANY,
    currency: "$",
    price: {
      startPrice: 2200,
      pledgePrice: 1100,
      buyoutPrice: 1320,
      branchPrice: 1250,
    },
    rent: {
      monopolyRent: 270,
      baseRent: 180,
      oneStar: 900,
      twoStar: 2500,
      freeStar: 7000,
      fourStar: 8750,
      bigStar: 10500,
      paymentMultiplier: 0,
    },
  },
  {
    fieldId: 23,
    fieldPosition: 22,
    fieldSpecial: 1,
    fieldGroup: null,
    fieldCorner: undefined,
    fieldLine: 2,
    isJail: false,
    level: 0,
    imgSrc: "fields/special/chance.png",
    name: "chance",
    description: "testDescription",
    fieldGroupName: "IT компании",
    type: FieldType.CHANCE,
    currency: "$",
    price: null,
    rent: null,
  },
  {
    fieldId: 24,
    fieldPosition: 23,
    fieldSpecial: null,
    fieldGroup: 5,
    fieldCorner: undefined,
    fieldLine: 2,
    isJail: false,
    level: 0,
    imgSrc: "fields/brands/5_airlines/lufthansa.svg",
    name: "lufthansa",
    description: "Стройте филиалы, чтобы увеличить ренту",
    fieldGroupName: "Авиалинии",
    type: FieldType.COMPANY,
    currency: "$",
    price: {
      startPrice: 2200,
      pledgePrice: 1100,
      buyoutPrice: 1320,
      branchPrice: 1250,
    },
    rent: {
      monopolyRent: 270,
      baseRent: 180,
      oneStar: 900,
      twoStar: 2500,
      freeStar: 7000,
      fourStar: 8750,
      bigStar: 10500,
      paymentMultiplier: 0,
    },
  },
  {
    fieldId: 25,
    fieldPosition: 24,
    fieldSpecial: null,
    fieldGroup: 5,
    fieldCorner: undefined,
    fieldLine: 2,
    isJail: false,
    level: 0,
    imgSrc: "fields/brands/5_airlines/british_airways.svg",
    name: "british_airways",
    description: "Стройте филиалы, чтобы увеличить ренту",
    fieldGroupName: "Авиалинии",
    type: FieldType.COMPANY,
    currency: "$",
    price: {
      startPrice: 2400,
      pledgePrice: 1200,
      buyoutPrice: 1440,
      branchPrice: 1250,
    },
    rent: {
      monopolyRent: 300,
      baseRent: 200,
      oneStar: 1000,
      twoStar: 3000,
      freeStar: 7500,
      fourStar: 9250,
      bigStar: 11000,
      paymentMultiplier: 0,
    },
  },
  {
    fieldId: 26,
    fieldPosition: 25,
    fieldSpecial: null,
    fieldGroup: 0,
    fieldCorner: undefined,
    fieldLine: 2,
    isJail: false,
    level: 0,
    imgSrc: "fields/brands/0_auto/ford.svg",
    name: "ford",
    description:
      "Рента зависит от количества автомобилей, которыми Вы владеете",
    fieldGroupName: "Автомобили",
    type: FieldType.AUTO,
    currency: "$",
    price: {
      startPrice: 2000,
      pledgePrice: 1000,
      buyoutPrice: 1200,
      branchPrice: 0,
    },
    rent: {
      monopolyRent: 0,
      baseRent: 250,
      oneStar: 500,
      twoStar: 1000,
      freeStar: 2000,
      fourStar: 0,
      bigStar: 0,
      paymentMultiplier: 0,
    },
  },
  {
    fieldId: 27,
    fieldPosition: 26,
    fieldSpecial: null,
    fieldGroup: 6,
    fieldCorner: undefined,
    fieldLine: 2,
    isJail: false,
    level: 0,
    imgSrc: "fields/brands/6_food/mcdonalds.svg",
    name: "mcdonalds",
    description: "Стройте филиалы, чтобы увеличить ренту",
    fieldGroupName: "Рестораны",
    type: FieldType.COMPANY,
    currency: "$",
    price: {
      startPrice: 2600,
      pledgePrice: 1300,
      buyoutPrice: 1560,
      branchPrice: 1500,
    },
    rent: {
      monopolyRent: 330,
      baseRent: 220,
      oneStar: 1100,
      twoStar: 3300,
      freeStar: 8000,
      fourStar: 9750,
      bigStar: 11500,
      paymentMultiplier: 0,
    },
  },
  {
    fieldId: 28,
    fieldPosition: 27,
    fieldSpecial: null,
    fieldGroup: 6,
    fieldCorner: undefined,
    fieldLine: 2,
    isJail: false,
    level: 0,
    imgSrc: "fields/brands/6_food/burger_king.svg",
    name: "burger_king",
    description: "Стройте филиалы, чтобы увеличить ренту",
    fieldGroupName: "Рестораны",
    type: FieldType.COMPANY,
    currency: "$",
    price: {
      startPrice: 2800,
      pledgePrice: 1400,
      buyoutPrice: 1680,
      branchPrice: 1500,
    },
    rent: {
      monopolyRent: 360,
      baseRent: 240,
      oneStar: 1200,
      twoStar: 3600,
      freeStar: 8500,
      fourStar: 10250,
      bigStar: 12000,
      paymentMultiplier: 0,
    },
  },
  {
    fieldId: 29,
    fieldPosition: 28,
    fieldSpecial: null,
    fieldGroup: 9,
    fieldCorner: undefined,
    fieldLine: 2,
    isJail: false,
    level: 0,
    imgSrc: "fields/brands/9_games/rovio.svg",
    name: "rovio",
    description: "Рента зависит от количества IT компаний",
    fieldGroupName: "IT компании",
    type: FieldType.IT,
    currency: "x",
    price: {
      startPrice: 1500,
      pledgePrice: 750,
      buyoutPrice: 900,
      branchPrice: 0,
    },
    rent: {
      monopolyRent: 0,
      baseRent: 100,
      oneStar: 250,
      twoStar: 0,
      freeStar: 0,
      fourStar: 0,
      bigStar: 0,
      paymentMultiplier: 1,
    },
  },
  {
    fieldId: 30,
    fieldPosition: 29,
    fieldSpecial: null,
    fieldGroup: 6,
    fieldCorner: undefined,
    fieldLine: 2,
    isJail: false,
    level: 0,
    imgSrc: "fields/brands/6_food/kfc.svg",
    name: "kfc",
    description: "Стройте филиалы, чтобы увеличить ренту",
    fieldGroupName: "Рестораны",
    type: FieldType.COMPANY,
    currency: "$",
    price: {
      startPrice: 2800,
      pledgePrice: 1400,
      buyoutPrice: 1680,
      branchPrice: 1500,
    },
    rent: {
      monopolyRent: 360,
      baseRent: 240,
      oneStar: 1200,
      twoStar: 3600,
      freeStar: 8500,
      fourStar: 10250,
      bigStar: 1200,
      paymentMultiplier: 0,
    },
  },
  {
    fieldId: 31,
    fieldPosition: 30,
    fieldSpecial: 1,
    fieldGroup: null,
    fieldCorner: 3,
    fieldLine: null,
    isJail: false,
    level: 0,
    imgSrc: "fields/special/goToJail.png",
    name: "arest",
    description: "testDescription",
    fieldGroupName: "IT компании",
    type: FieldType.JAIL,
    currency: "$",
    price: null,
    rent: null,
  },
  {
    fieldId: 32,
    fieldPosition: 31,
    fieldSpecial: null,
    fieldGroup: 7,
    fieldCorner: undefined,
    fieldLine: 3,
    isJail: false,
    level: 0,
    imgSrc: "fields/brands/7_hotels/holiday_inn.svg",
    name: "holiday_inn",
    description: "Стройте филиалы, чтобы увеличить ренту",
    fieldGroupName: "Отели",
    type: FieldType.COMPANY,
    currency: "$",
    price: {
      startPrice: 3000,
      pledgePrice: 1500,
      buyoutPrice: 1800,
      branchPrice: 1750,
    },
    rent: {
      monopolyRent: 390,
      baseRent: 260,
      oneStar: 1300,
      twoStar: 3600,
      freeStar: 9000,
      fourStar: 11000,
      bigStar: 12750,
      paymentMultiplier: 0,
    },
  },
  {
    fieldId: 33,
    fieldPosition: 32,
    fieldSpecial: null,
    fieldGroup: 7,
    fieldCorner: undefined,
    fieldLine: 3,
    isJail: false,
    level: 0,
    imgSrc: "fields/brands/7_hotels/radisson_blu.svg",
    name: "radisson_blu",
    description: "Стройте филиалы, чтобы увеличить ренту",
    fieldGroupName: "Отели",
    type: FieldType.COMPANY,
    currency: "$",
    price: {
      startPrice: 3000,
      pledgePrice: 1500,
      buyoutPrice: 1800,
      branchPrice: 1750,
    },
    rent: {
      monopolyRent: 390,
      baseRent: 260,
      oneStar: 1300,
      twoStar: 3900,
      freeStar: 9000,
      fourStar: 11000,
      bigStar: 12750,
      paymentMultiplier: 0,
    },
  },
  {
    fieldId: 34,
    fieldPosition: 33,
    fieldSpecial: 1,
    fieldGroup: null,
    fieldCorner: undefined,
    fieldLine: 3,
    isJail: false,
    level: 0,
    imgSrc: "fields/special/chance_rotated.png",
    name: "chance_rotated",
    description: "testDescription",
    fieldGroupName: "IT компании",
    type: FieldType.CHANCE,
    currency: "$",
    price: null,
    rent: null,
  },
  {
    fieldId: 35,
    fieldPosition: 34,
    fieldSpecial: null,
    fieldGroup: 7,
    fieldCorner: undefined,
    fieldLine: 3,
    isJail: false,
    level: 0,
    imgSrc: "fields/brands/7_hotels/novotel.svg",
    name: "novotel",
    description: "Стройте филиалы, чтобы увеличить ренту",
    fieldGroupName: "Отели",
    type: FieldType.COMPANY,
    currency: "$",
    price: {
      startPrice: 3200,
      pledgePrice: 1600,
      buyoutPrice: 1920,
      branchPrice: 1750,
    },
    rent: {
      monopolyRent: 420,
      baseRent: 280,
      oneStar: 1500,
      twoStar: 4500,
      freeStar: 10000,
      fourStar: 12000,
      bigStar: 14000,
      paymentMultiplier: 0,
    },
  },
  {
    fieldId: 36,
    fieldPosition: 35,
    fieldSpecial: null,
    fieldGroup: 0,
    fieldCorner: undefined,
    fieldLine: 3,
    isJail: false,
    level: 0,
    imgSrc: "fields/brands/0_auto/land_rover.svg",
    name: "land_rover",
    description:
      "Рента зависит от количества автомобилей, которыми Вы владеете",
    fieldGroupName: "Автомобили",
    type: FieldType.AUTO,
    currency: "$",
    price: {
      startPrice: 2000,
      pledgePrice: 1000,
      buyoutPrice: 1200,
      branchPrice: 0,
    },
    rent: {
      monopolyRent: 0,
      baseRent: 250,
      oneStar: 500,
      twoStar: 1000,
      freeStar: 2000,
      fourStar: 0,
      bigStar: 0,
      paymentMultiplier: 0,
    },
  },
  {
    fieldId: 37,
    fieldPosition: 36,
    fieldSpecial: 1,
    fieldGroup: null,
    fieldCorner: undefined,
    fieldLine: 3,
    isJail: false,
    level: 0,
    imgSrc: "fields/special/tax_luxury.png",
    name: "tax_luxury",
    description: "testDescription",
    fieldGroupName: "IT компании",
    type: FieldType.TAX,
    currency: "$",
    price: { startPrice: 0, pledgePrice: 0, buyoutPrice: 0, branchPrice: 0 },
    rent: {
      monopolyRent: 0,
      baseRent: 1000,
      oneStar: 0,
      twoStar: 0,
      freeStar: 0,
      fourStar: 0,
      bigStar: 0,
      paymentMultiplier: 0,
    },
  },
  {
    fieldId: 38,
    fieldPosition: 37,
    fieldSpecial: null,
    fieldGroup: 8,
    fieldCorner: undefined,
    fieldLine: 3,
    isJail: false,
    level: 0,
    imgSrc: "fields/brands/8_smartphones/apple.svg",
    name: "apple",
    description: "Стройте филиалы, чтобы увеличить ренту",
    fieldGroupName: "Электроника",
    type: FieldType.COMPANY,
    currency: "$",
    price: {
      startPrice: 3500,
      pledgePrice: 1750,
      buyoutPrice: 2100,
      branchPrice: 2000,
    },
    rent: {
      monopolyRent: 500,
      baseRent: 350,
      oneStar: 1750,
      twoStar: 5000,
      freeStar: 11000,
      fourStar: 13000,
      bigStar: 15000,
      paymentMultiplier: 0,
    },
  },
  {
    fieldId: 39,
    fieldPosition: 38,
    fieldSpecial: 1,
    fieldGroup: null,
    fieldCorner: undefined,
    fieldLine: 3,
    isJail: false,
    level: 0,
    imgSrc: "fields/special/chance_rotated.png",
    name: "chance_rotated",
    description: "testDescription",
    fieldGroupName: "IT компании",
    type: FieldType.CHANCE,
    currency: "$",
    price: null,
    rent: null,
  },
  {
    fieldId: 40,
    fieldPosition: 39,
    fieldSpecial: null,
    fieldGroup: 8,
    fieldCorner: undefined,
    fieldLine: 3,
    isJail: false,
    level: 0,
    imgSrc: "fields/brands/8_smartphones/nokia.svg",
    name: "nokia",
    description: "Стройте филиалы, чтобы увеличить ренту",
    fieldGroupName: "Электроника",
    type: FieldType.COMPANY,
    currency: "$",
    price: {
      startPrice: 4000,
      pledgePrice: 2000,
      buyoutPrice: 2400,
      branchPrice: 2000,
    },
    rent: {
      monopolyRent: 1000,
      baseRent: 500,
      oneStar: 2000,
      twoStar: 6000,
      freeStar: 14000,
      fourStar: 17000,
      bigStar: 20000,
      paymentMultiplier: 0,
    },
  },
];
