export enum ErrorCode {
  "Not enough money" = 101,
  "Company has owner" = 102,
  "Wrong tranactionId" = 103,
  "Not user field" = 104,
  "Field is mortgaged" = 105,
  "Not my turn" = 106,
  "Cannot mortgage field" = 107,
  "Cannot unmortgage field" = 108,
  "Max field level" = 109,
  "Cannot build branch" = 110,
  "No monopoly" = 111,
  "Cannot start auction" = 112,
  "Cannot proceed contract" = 113,
  "Room already exists" = 114,
  "Room doesn`t exist" = 115,
  "Max players reached" = 116,
  "Only for VIP" = 117,
  "Login to create room" = 401,
}
